### ISSUE TITLE
Send Telnet command via Custom Command

### ISSUE THREAD

**Issue by Keksstar** [CasparCG/client#174] opened 2015-10-10 14:48 UTC
Would be nice to have the ability to send out Telnet commands via "Custom Command" in the Client. (or with a new "Telnet" Tool)
A lot of devices in the broadcast world can understand Telnet commands. Would be great to have a way to control them via commands.

**Comment by mauricev78** [comment] 2015-10-30 10:19
PLUS ONE

**Comment by aladinko** [comment] 2016-05-17 12:01
Plus One

**Comment by dimitry-ishenko** [comment] 2016-05-17 20:10
From what I understand Custom Commands are sent to the CasparCG server. We need Custom Shell Command for this. See issue #199.

**Comment by Julusian** [comment] 2023-12-14 00:26
This is either a duplicate of #199, or can be handled by using some other software which this client talks to over http/osc

**Closed by Julusian** 2023-12-14 00:25 UTC
