### ISSUE TITLE
Ability to have parameters at group level

### ISSUE THREAD

**Issue by jesperstarkar** [CasparCG/client#141] opened 2015-03-09 15:47 UTC
Groups are more and more used. Some functionality like autoplay (and now play-command for looping) are only possible by using groups. However, groups have the drawback that parameters are hidden away one level to deep.

Non-super-users are more likely to do tasks by triggering pre-defined groups (presets). Some times though, they need to change file-names, template fields or other parameters.

It would have been super if groups had parameters, that acted like variables for paramters of the items within the group... Or, if you on child-elements could break out given parameters and control them directly and natively via the right kind of UI control.

**Comment by Keksstar** [comment] 2015-10-10 14:52
Group Parameters would make the life easier. Good request

**Comment by dotarmin** [comment] 2017-08-31 09:41
I guess this is an duplicate of issue #55.

**Comment by dotarmin** [comment] 2019-02-25 14:06
I'm closing this issue in favour of #55

**Closed by dotarmin** 2019-02-25 14:06 UTC
Labels: duplicate
