### ISSUE TITLE
Client crashes when ATEM config is restored

### ISSUE THREAD

**Issue by premultiply** [CasparCG/client#232] opened 2017-03-16 10:18 UTC
When the Client is connected to an ATEM switcher and the complete switcher configuration is restored from the Blackmagic Design ATEM Software Control the Client crashes immediately.

**Comment by lassewamsler** [comment] 2017-04-02 11:21
I have the same issue. I have tried to downgrade the ATEM Switcher to 6.8.2 - the issue is still there. I have the issue on Caspar CG Client 2.0.8 - on 2.0.7 the client is running, but can't connect to the ATEM (ver. 6.0.8 to 7.0.3).

**Comment by dotarmin** [comment] 2017-09-01 07:35
Thanks for reporting this! You're not the only one having issues with the ATEM integration. We have multiple reports about ATEM issues with CasparCG Client and we must have a look into it asap.

Thanks!

/Armin

**Comment by dedicatedbroadcastsolutions** [comment] 2018-07-13 18:37
Any progress on this?

**Comment by dedicatedbroadcastsolutions** [comment] 2018-07-16 07:39
This is most likely fixed with pull request #251 for both branches on here. Someone needs to update the qatemcontrol libraries for linux and mac, but I got it fixed for windows.

Here are a couple of builds I put together for windows. These were forked from the latest commits on each branch.

Here is a build with the included fix.
Master Branch 2.0.8 (current)
https://goo.gl/837uVn

Next Branch 2.0.9
https://goo.gl/yQteYB

These links will probably go dead once there are official builds including these changes.

**Comment by bencredible** [comment] 2019-04-19 16:17
I could be mistaken but it looks like the 2.2.0 RC NEXT client has this problem re-introduced... At least when I run the old client with the patch it is fine, but if I have an ATEM switcher attached and run the new client it crashes on launch. Kill the ATEM switcher and the new client works great.

**Comment by Julusian** [comment] 2023-12-13 23:51
ATEM support is being remove in 2.3.0 of this client, to improve stability and minimise maintenance costs.

**Closed by Julusian** 2023-12-13 23:51 UTC
Labels: bug
