### ISSUE TITLE
Client crashes with ATEM device

### ISSUE THREAD

**Issue by mauricev78** [CasparCG/Client#151] opened 2015-06-16 18:57 UTC
when adding a ATEM switcher (television studio latests firmware) 
the client crashes most of the time immediately.
if not it will crash later while adding Atem Cue's
if you try to open the client again after a crash it crashes immediately

only cure seams to be to delete the complete  ".Caspar" folder.

this is what I find after the crash in the log file
[2015-06-16 20:44:16.895] [878] [D] Starting CasparCG Client 2.0.8.e1bfc52211
[2015-06-16 20:44:17.020] [878] [D] Using SQLite database
[2015-06-16 20:44:17.145] [878] [D] LibraryWidget::repositoryRundown 0 msec
[2015-06-16 20:44:17.145] [878] [D] Using live arguments: --no-osd --ignore-config --verbose=-1 --network-caching=1000 --no-audio
[2015-06-16 20:44:18.790] [878] [D] Refreshing library...
[33m[2015-06-16 20:44:18.912] [878] [W] QColor::setHsvF: HSV parameters out of range[0m
[33m[2015-06-16 20:44:18.915] [878] [W] QColor::setHsvF: HSV parameters out of range[0m
[2015-06-16 20:44:18.917] [878] [D] [doCCdP] Unknown camera feature: 8
[2015-06-16 20:44:18.920] [878] [D] [onCCdP] Unknown adjustment domain: 4
[2015-06-16 20:44:18.922] [878] [D] [doCCdP] Unknown camera feature: 8
[2015-06-16 20:44:18.924] [878] [D] [onCCdP] Unknown adjustment domain: 4
[2015-06-16 20:44:18.926] [878] [D] [doCCdP] Unknown camera feature: 8
[2015-06-16 20:44:18.928] [878] [D] [onCCdP] Unknown adjustment domain: 4
[2015-06-16 20:44:18.931] [878] [D] [doCCdP] Unknown camera feature: 8
[2015-06-16 20:44:18.933] [878] [D] [onCCdP] Unknown adjustment domain: 4
[2015-06-16 20:44:18.935] [878] [D] [doCCdP] Unknown camera feature: 8
[2015-06-16 20:44:18.937] [878] [D] [onCCdP] Unknown adjustment domain: 4
[2015-06-16 20:44:18.940] [878] [D] [doCCdP] Unknown camera feature: 8
[2015-06-16 20:44:18.942] [878] [D] [onCCdP] Unknown adjustment domain: 4

kind regards
maurice

**Comment by Zebiolo** [comment] 2015-06-16 19:06
Have you updated to the latest ATEM firmware?

**Comment by mauricev78** [comment] 2015-06-16 19:11
Yes

running on 6.4.1

**Comment by Zebiolo** [comment] 2015-06-24 11:00
I have updated the ATEM library. Can you try the latest git build from builds.casparcg.com and see if the problem is solved. If so, please close the issue.

**Comment by mauricev78** [comment] 2015-06-24 11:39
Will have a look later this week.

thanks

**Comment by mauricev78** [comment] 2015-06-24 20:24
It seams to work

thanks

**Closed** 2015-08-18 12:25 UTC
